package nl.ferron.copilotcontextbridge.context

import java.nio.charset.StandardCharsets
import java.nio.file.Path
import java.util.concurrent.TimeUnit

/** Produces factual branch/working-tree context without requiring a manual diff text field. */
class GitBranchContextResolver(
    private val repositoryRoot: Path,
) {
    data class Result(
        val repositoryRoot: Path,
        val branch: String,
        val baseBranch: String,
        val mergeBase: String,
        val head: String,
        val changedPaths: List<String>,
        val markdown: String,
        val warnings: List<String>,
    )

    fun resolve(requestedPaths: Set<String>? = null): Result? {
        val topLevel = command("rev-parse", "--show-toplevel").takeIf { it.exitCode == 0 }?.output?.trim() ?: return null
        val root = Path.of(topLevel).toAbsolutePath().normalize()
        if (root != repositoryRoot.toAbsolutePath().normalize()) return null
        val branch = successful("branch", "--show-current").ifBlank { "detached HEAD" }
        val head = successful("rev-parse", "HEAD").ifBlank { "unavailable" }
        val remoteDefault = successful("symbolic-ref", "--short", "refs/remotes/origin/HEAD").removePrefix("origin/")
        val base =
            listOf(remoteDefault, "main", "master").firstOrNull { it.isNotBlank() && command("rev-parse", "--verify", it).exitCode == 0 }
                ?: "HEAD"
        val mergeBase = successful("merge-base", "HEAD", base).ifBlank { head }
        val committed = lines("diff", "--name-only", "$mergeBase...HEAD")
        val working = lines("diff", "--name-only", "HEAD")
        val untracked = lines("ls-files", "--others", "--exclude-standard")
        val allChanged =
            (committed + working + untracked)
                .map(::normalizePath)
                .filter(String::isNotBlank)
                .distinct()
                .sorted()
        val selected = requestedPaths?.let { wanted -> allChanged.filter { it in wanted } } ?: allChanged
        val warnings = mutableListOf<String>()
        val noSelectedMatch = requestedPaths != null && selected.isEmpty()
        val committedDiff =
            if (noSelectedMatch) {
                ""
            } else {
                limited(
                    successful("diff", "--no-ext-diff", "--unified=3", "$mergeBase...HEAD", "--", *selected.toTypedArray()),
                    warnings,
                )
            }
        val workingDiff =
            if (noSelectedMatch) {
                ""
            } else {
                limited(
                    successful("diff", "--no-ext-diff", "--unified=3", "HEAD", "--", *selected.toTypedArray()),
                    warnings,
                )
            }
        val commits = successful("log", "--format=%h %s", "$mergeBase..HEAD").ifBlank { "No branch-only commits." }
        val status =
            if (noSelectedMatch) {
                "No selected changed paths matched."
            } else {
                successful("status", "--short", "--", *selected.toTypedArray()).ifBlank { "Clean for selected paths." }
            }
        val markdown =
            buildString {
                appendLine("# Pull request branch context")
                appendLine()
                appendLine("Generated by Copilot Context Bridge from Git. Do not invent changes or test results not shown here.")
                appendLine()
                appendLine("- Current branch: `$branch`")
                appendLine("- Base branch: `$base`")
                appendLine("- Merge base: `$mergeBase`")
                appendLine("- HEAD: `$head`")
                appendLine()
                appendLine("## Changed files")
                if (selected.isEmpty()) appendLine("- None") else selected.forEach { appendLine("- `$it`") }
                appendLine()
                appendLine("## Commits")
                appendLine("```text")
                appendLine(commits)
                appendLine("```")
                appendLine()
                appendLine("## Working tree status")
                appendLine("```text")
                appendLine(status)
                appendLine("```")
                appendLine()
                appendLine("## Committed branch diff")
                appendLine("```diff")
                appendLine(committedDiff.ifBlank { "No committed diff for selected paths." })
                appendLine("```")
                appendLine()
                appendLine("## Uncommitted working-tree diff")
                appendLine("```diff")
                appendLine(workingDiff.ifBlank { "No uncommitted diff for selected paths." })
                appendLine("```")
                appendLine()
                appendLine("## Required PR output template")
                appendLine("### Title\n<Concise imperative title>\n")
                appendLine("### Summary\n- <main change>\n")
                appendLine("### Why\n<Why this change is needed>\n")
                appendLine("### Changes\n- <implementation change>\n")
                appendLine("### Testing\n- <test actually performed, or Not run>\n")
                appendLine("### Risks / impact\n<Concise risks or None>\n")
                appendLine("### Reviewer focus\n<What reviewers should pay attention to>")
            }
        return Result(root, branch, base, mergeBase, head, selected, markdown, warnings)
    }

    private fun lines(vararg arguments: String): List<String> =
        successful(*arguments)
            .lineSequence()
            .map(String::trim)
            .filter(String::isNotBlank)
            .toList()

    private fun successful(vararg arguments: String): String =
        command(*arguments)
            .takeIf { it.exitCode == 0 }
            ?.output
            .orEmpty()
            .trim()

    private fun command(vararg arguments: String): CommandResult {
        val process =
            ProcessBuilder(listOf("git", "-C", repositoryRoot.toString()) + arguments)
                .redirectErrorStream(true)
                .start()
        if (!process.waitFor(10, TimeUnit.SECONDS)) {
            process.destroyForcibly()
            return CommandResult(-1, "Git command timed out.")
        }
        return CommandResult(process.exitValue(), String(process.inputStream.readAllBytes(), StandardCharsets.UTF_8))
    }

    private fun limited(
        value: String,
        warnings: MutableList<String>,
    ): String {
        val maximum = 2_000_000
        if (value.length <= maximum) return value
        warnings += "Git diff exceeded 2,000,000 characters and was truncated."
        return value.take(maximum) + "\n\n[Diff truncated by Copilot Context Bridge]"
    }

    private fun normalizePath(value: String): String = value.replace('\\', '/').trimStart('/')

    private data class CommandResult(
        val exitCode: Int,
        val output: String,
    )
}
